-- Harus Custom Tables Migration for Hercules
-- Auto-generated migration script
USE `harus`;

-- Custom table: char_pvp
CREATE TABLE IF NOT EXISTS `char_pvp` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `kill_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `death_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `score` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: char_pk
CREATE TABLE IF NOT EXISTS `char_pk` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `kill_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `death_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `score` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: char_bg
CREATE TABLE IF NOT EXISTS `char_bg` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `top_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `damage_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `damage_received` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `skulls` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ti_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ti_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ti_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `eos_flags` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `eos_bases` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `eos_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `eos_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `eos_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_killed` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_flags` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `boss_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `td_kills` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `td_deaths` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `td_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `td_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `td_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_stole` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_captured` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_droped` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sc_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_taken` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_captured` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_droped` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ctf_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `emperium_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `barricade_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `gstone_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `cq_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `cq_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ru_captures` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ru_wins` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ru_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `kill_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `death_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `win` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `leader_win` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `leader_lost` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `leader_tie` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `deserter` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `score` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `points` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `rank_points` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `rank_games` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sp_heal_potions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hp_heal_potions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `yellow_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `red_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `blue_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `poison_bottles` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acid_demostration` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acid_demostration_fail` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `support_skills_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `healing_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `wrong_support_skills_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `wrong_healing_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `sp_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `zeny_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `spiritb_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ammo_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: char_wstats
CREATE TABLE IF NOT EXISTS `char_wstats` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `kill_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `death_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `score` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `top_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `damage_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `damage_received` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `emperium_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `guardian_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `barricade_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `gstone_damage` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `emperium_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `guardian_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `barricade_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `gstone_kill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `sp_heal_potions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `hp_heal_potions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `yellow_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `red_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `blue_gemstones` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `poison_bottles` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acid_demostration` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acid_demostration_fail` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `support_skills_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `healing_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `wrong_support_skills_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `wrong_healing_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `sp_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `zeny_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `spiritb_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ammo_used` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: skill_count
CREATE TABLE IF NOT EXISTS `skill_count` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`, `id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: bg_skill_count
CREATE TABLE IF NOT EXISTS `bg_skill_count` (
  `char_id` INT(11) UNSIGNED NOT NULL,
  `id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`, `id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: char_bg_log
CREATE TABLE IF NOT EXISTS `char_bg_log` (
  `time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `killer` VARCHAR(23) NOT NULL DEFAULT '',
  `killer_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `killed` VARCHAR(23) NOT NULL DEFAULT '',
  `killed_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `map` VARCHAR(11) NOT NULL DEFAULT '',
  `skill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: char_woe_log
CREATE TABLE IF NOT EXISTS `char_woe_log` (
  `time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `killer` VARCHAR(23) NOT NULL DEFAULT '',
  `killer_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `killed` VARCHAR(23) NOT NULL DEFAULT '',
  `killed_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `map` VARCHAR(11) NOT NULL DEFAULT '',
  `skill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: ippremium
CREATE TABLE IF NOT EXISTS `ippremium` (
  `ip` VARCHAR(100) NOT NULL DEFAULT '',
  `level` INT(11) NOT NULL DEFAULT '0',
  KEY `ip` (`ip`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: item_serials
CREATE TABLE IF NOT EXISTS `item_serials` (
  `nameid` INT(11) NOT NULL DEFAULT '0',
  `serial` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`nameid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: pvpm_data
CREATE TABLE IF NOT EXISTS `pvpm_data` (
  `id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `kills` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `dies` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ratio` INT(11) NOT NULL DEFAULT '0',
  `leader` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `annc` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ban` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `type` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  KEY `id` (`id`),
  KEY `kills` (`kills`),
  KEY `dies` (`dies`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: pvpm_lang
CREATE TABLE IF NOT EXISTS `pvpm_lang` (
  `id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `lang` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `str` VARCHAR(255) NOT NULL DEFAULT '',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Custom table: pvpm_map
CREATE TABLE IF NOT EXISTS `pvpm_map` (
  `id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `map` VARCHAR(255) NOT NULL DEFAULT 'NULL',
  `type` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `noguild` INT(11) NOT NULL DEFAULT '0',
  KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

