$enc = [System.Text.Encoding]::GetEncoding(1252)
$NL = "`r`n"
$T = "`t"

# Caracteres especiais em Latin-1
$a1 = [char]0xE1  # á
$a3 = [char]0xE3  # ã
$a2 = [char]0xE2  # â
$ea = [char]0xEA  # ê
$e9 = [char]0xE9  # é
$ed = [char]0xED  # í
$f3 = [char]0xF3  # ó
$e7 = [char]0xE7  # ç
$bb = [char]0xBB  # »

$lines = @(
"prontera,156,196,5`tscript`tMestra das Classes::JobMaster`t743,{",
"${T}if(BaseLevel && JobLevel > 1){",
"${T}javirou:",
"${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}if (Class > 22 && Class < 26 || Class > 4007 && Class < 4023 || Class > 4029 && Class < 4046 || Class > 4046 && Class <= 4049)",
"${T}{",
"${T}${T}mes `"Que bom te ver de novo ^0088FF`"+strcharinfo(0)+`"^000000!`";",
"${T}${T}mes `"O dia est${a1} lindo, n${a3}o acha?`";",
"${T}${T}close;",
"${T}}",
"${T}if (SkillPoint)",
"${T}{",
"${T}${T}mes `"Voc${ea} precisa utilizar todos os seus pontos de habilidade antes de mudar de classe.`";",
"${T}${T}close;",
"${T}}",
"${T}if (!Class || Class == 4023)",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 10, 0;",
"${T}${T}mes `"Ol${a1} ^0088FF`"+strcharinfo(0)+`"^000000, vejo que voc${ea} ${e9} apenas um `"+jobname(Class)+`"!`";",
"${T}${T}mes `"Voc${ea} est${a1} apto a mudar de classe. Qual deseja se tornar?`";",
"${T}${T}next;",
"${T}${T}if (!Class)",
"${T}${T}{",
"${T}${T}${T}select (`"^0088FF[${bb}]^000000 Espadachim:^0088FF[${bb}]^000000 Mago:^0088FF[${bb}]^000000 Arqueiro:^0088FF[${bb}]^000000 Novi${e7}o:^0088FF[${bb}]^000000 Mercador:^0088FF[${bb}]^000000 Gatuno:^0088FF[${bb}]^000000 Taekwon:^0088FF[${bb}]^000000 Justiceiro:^0088FF[${bb}]^000000 Ninja:^0088FF[${bb}]^000000 Super Aprendiz`");",
"${T}${T}${T}set .@chg, ((@menu == 7) ? 4046 : ((@menu == 8 || @menu == 9) ? (16+@menu) : ((@menu == 10) ? 23 : @menu)));",
"${T}${T}}",
"${T}${T}else",
"${T}${T}{",
"${T}${T}${T}select (`"Mini Espadachim:Mini Mago:Mini Arqueiro:Mini Novi${e7}o:Mini Mercador:Mini Gatuno:Mini Super Aprendiz`");",
"${T}${T}${T}set .@chg, ((@menu == 7) ? 4045 : (4023+@menu));",
"${T}${T}}",
"${T}${T}callsub F_ChangeJob, set (lastjob1, .@chg);",
"${T}}",
"${T}else if (Class > 0 && (Class < 7 || Class == 4046))",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 40, 0;",
"${T}${T}mes `"Vejo que voc${ea} voltou; e mais forte!`";",
"${T}${T}mes `"Pois bem, que classe deseja seguir agora?`";",
"${T}${T}switch (Class)",
"${T}${T}{",
"${T}${T}${T}case 1:",
"${T}${T}${T}${T}${T}setarray .@c[0],7,14;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}${T}${T}",
"${T}${T}${T}case 2:",
"${T}${T}${T}${T}${T}setarray .@c[0],9,16;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}${T}${T}",
"${T}${T}${T}case 3:",
"${T}${T}${T}${T}${T}if (Sex)",
"${T}${T}${T}${T}${T}${T}setarray .@c[0],11,19;",
"${T}${T}${T}${T}${T}else",
"${T}${T}${T}${T}${T}${T}setarray .@c[0],11,20;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}${T}${T}",
"${T}${T}${T}case 4:",
"${T}${T}${T}${T}${T}setarray .@c[0],8,15;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}",
"${T}${T}${T}case 5:",
"${T}${T}${T}${T}${T}setarray .@c[0],10,18;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}${T}${T}",
"${T}${T}${T}case 6:",
"${T}${T}${T}${T}${T}setarray .@c[0],12,17;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}${T}${T}${T}",
"${T}${T}${T}case 4046:",
"${T}${T}${T}${T}${T}setarray .@c[0],4047,4049;",
"${T}${T}${T}${T}${T}break;",
"${T}${T}}",
"${T}${T}next;",
"${T}${T}select (jobname(.@c[0])+`"`"`,`"`"+jobname(.@c[1]));",
"${T}${T}callsub F_ChangeJob, set(lastjob, .@c[(@menu-1)]);",
"${T}}",
"${T}else if (Class > 6 && Class < 22)",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 50, 1;",
"${T}${T}mes `"Vejo que voc${ea} est${a1} bastante forte!`";",
"${T}${T}mes `"Gostaria de renascer?`";",
"${T}${T}next;",
"${T}${T}if (select (`"^00CC00[${bb}]^000000 Sim:^FF0000[${bb}]^000000 N${a3}o`") == 2)",
"${T}${T}${T}close;",
"${T}${T}mes `"[^010849===^000000 ^016B14`"+strnpcinfo(1)+`"^000000 ^010849===^000000]`";",
"${T}${T}jobchange 4001;",
"${T}${T}resetlvl(1);",
"${T}${T}mes `"Voc${ea} ganhar${a1} 100 Pontos de Atributo, e algumas habilidades`";",
"${T}${T}mes `"para ajudar-lhe em sua jornada.`";",
"${T}${T}close;",
"${T}}",
"${T}else if (Class == 4001)",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 10, 0;",
"${T}${T}mes `"Voc${ea} voltou t${a3}o r${a1}pido e est${a1} evoluindo muito ^^ ...`";",
"${T}${T}next;",
"${T}${T}callsub F_ChangeJob, (lastjob1+4001);",
"${T}}",
"${T}else if (Class > 4001 && Class < 4008)",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 40, 0;",
"${T}${T}mes `"Voc${ea} est${a1} quase chegando ao grau m${a1}ximo de evolu${e7}${a3}o.`";",
"${T}${T}mes `"E ent${a3}o...`";",
"${T}${T}next;",
"${T}${T}callsub F_ChangeJob, (lastjob+4001);",
"${T}}",
"${T}",
"${T}if (Class > 4023 && Class < 4030)",
"${T}{",
"${T}${T}callsub F_ReqBaseJobLevel, 40, 0;",
"${T}${T}mes `"Vejo que voc${ea} voltou; e mais forte!`";",
"${T}${T}mes `"Pois bem, que classe deseja seguir agora?`";",
"${T}${T}next;",
"${T}${T}switch (Class)",
"${T}${T}{",
"${T}${T}${T}case 4024:",
"${T}${T}${T}${T}setarray .@c[0], 4030, 4037;",
"${T}${T}${T}${T}break;",
"${T}${T}${T}${T}",
"${T}${T}${T}case 4025:",
"${T}${T}${T}${T}setarray .@c[0], 4032, 4039;",
"${T}${T}${T}${T}break;",
"${T}${T}${T}${T}",
"${T}${T}${T}case 4026:",
"${T}${T}${T}${T}if (Sex)",
"${T}${T}${T}${T}${T}setarray .@c[0], 4034, 4042;",
"${T}${T}${T}${T}else",
"${T}${T}${T}${T}${T}setarray .@c[0], 4034, 4043;",
"${T}${T}${T}${T}break;",
"${T}${T}${T}${T}",
"${T}${T}${T}case 4027:",
"${T}${T}${T}${T}setarray .@c[0], 4031, 4038;",
"${T}${T}${T}${T}break;",
"${T}${T}${T}${T}",
"${T}${T}${T}case 4028:",
"${T}${T}${T}${T}setarray .@c[0], 4033, 4041;",
"${T}${T}${T}${T}break;",
"${T}${T}${T}",
"${T}${T}${T}case 4029:",
"${T}${T}${T}${T}setarray .@c[0], 4035, 4040;",
"${T}${T}${T}${T}break;",
"${T}${T}}",
"${T}${T}select (jobname(.@c[0])+`"`"`,`"`"+jobname(.@c[1]));",
"${T}${T}callsub F_ChangeJob, .@c[@menu-1];",
"${T}}",
"${T}${T}",
"${T}F_ChangeJob:",
"${T}${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}${T}if (BaseLevel < 45 && (getarg(0) == 23 || getarg(0) == 4045))",
"${T}${T}{",
"${T}${T}${T}mes `"Voc${ea} precisa ter pelo menos N${ed}vel de Base 45 para poder mudar de classe.`";",
"${T}${T}${T}close;",
"${T}${T}}",
"${T}${T}mes `"Voc${ea} tem certeza que deseja se tornar `"+jobname(getarg(0))+`"?`";",
"${T}${T}if (select (`"^00CC00[${bb}]^000000 Sim:^FF0000[${bb}]^000000 N${a3}o`") == 2)",
"${T}${T}${T}close;",
"${T}${T}next;",
"${T}${T}jobchange getarg(0);",
"${T}${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}${T}mes `"Parab${e9}ns, agora voc${ea} ${e9} um ^0000cd`"+jobname(getarg(0))+`"^000000!`";",
"${T}${T}close;",
"${T}return;",
"${T}",
"${T}F_ReqBaseJobLevel:",
"${T}${T}if (((getarg(1))?BaseLevel:99) < 99 || JobLevel < getarg(0))",
"${T}${T}{",
"${T}${T}${T}mes `"Voc${ea} precisa ter pelo menos `"+((getarg(1,0))?`"N${ed}vel de Base 99 e `":`"`")+`"N${ed}vel de Classe `"+getarg(0)+`" para poder mudar de classe.`";",
"${T}${T}${T}close;",
"${T}${T}}",
"${T}return;",
"${T}",
"}",
"${T}if(Class == 4023){",
"${T}callsub javirou;",
"${T}end;",
"${T}}",
"${T}if(Class > 0){",
"${T}callsub javirou;",
"${T}end;",
"${T}}",
"${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}mes `"Ol${a1} ^0088FF`"+strcharinfo(0)+`"^000000.`";",
"${T}mes `"Vejo que voc${ea} ${e9} um ^0000cdAprendiz^000000...`";",
"${T}mes `"Level de Base e Classe 1!`";",
"${T}mes `"Deseja se tornar um Mini-Aprendiz?`";",
"${T}switch(select(`"^00CC00[${bb}]^000000 Sim:^FF0000[${bb}]^000000 N${a3}o`")){",
"${T}${T}",
"${T}${T}case 1:",
"${T}${T}next;",
"${T}${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}${T}mes `"Voc${ea} tem certeza de sua escolha?`";",
"${T}${T}if(select(`"^00CC00[${bb}]^000000 Sim:^FF0000[${bb}]^000000 N${a3}o`")==2) close;",
"${T}${T}next;",
"${T}${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}${T}mes `"Parab${e9}ns, agora voc${ea} ${e9} um ^0000cdMini-Aprendiz^000000!`";",
"${T}${T}jobchange 4023;",
"${T}${T}close;",
"${T}${T}",
"${T}${T}case 2:",
"${T}${T}next;",
"${T}${T}${T}mes `"^016B14[`"+strnpcinfo(1)+`"]^000000`";",
"${T}${T}mes `"Lembre-se para se tornar um ^0000cdMini-Aprendiz^000000...`";",
"${T}${T}mes `"voc${ea} precisar ser aprendiz com ^FF0000Level de Base e Classe 1^000000!`";",
"${T}${T}close;",
"${T}${T}",
"",
"}",
"",
"OnInit:",
"${T}waitingroom `"Mestra das Classes`",0;",
"${T}end;",
"}",
"",
"//Campo inicial",
"new_1-3,86,175,4${T}duplicate(JobMaster)${T}Mestra das Classes#newmap1${T}743"
)

$content = $lines -join $NL
$bytes = $enc.GetBytes($content)
[System.IO.File]::WriteAllBytes("C:\Users\nKorea\Desktop\Harus\Hercules\npc\ragnayokai\harus\gerais\jobmaster.txt", $bytes)
Write-Host "Feito! Bytes escritos: $($bytes.Length)"
