//--------------------------------------------------------------
// Easycore Works - Extended Vending Configuration
//--------------------------------------------------------------
// Note 1: Value is a config switch (on/off, yes/no or 1/0)
//--------------------------------------------------------------

// Extended Vending System [Lilith]
// Enable or disable extended vending system? (Note 1)
extended_vending: true

// Enable show broadcast info when player click vending board (Note 1)
show_broadcast_info: true

// Show currency's name in vending board? (Note 1)
show_item_vending: true

// Show more info about buying? (Note 1)
ex_vending_info: true

// Send a Vending Report to mailbox/rodex vendor? (Note 1)
ex_vending_report: true

// Allow to buy items with bound items? (Note 1)
// WARNING: Players might dupe items
ex_buying_bound: false

// Item ID for Zeny. Set to 0 if you don't want use Zeny.
item_zeny: 30000

// Item ID for Cash. Set to 0 if you don't want use Cash.
item_cash: 30001
